/**
 ******************************************************************************
 * @file    mx.c
 * @author  SRA - GPM
 * 
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an ODeV driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the ODeV framework.
 *
 *******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *******************************************************************************
 */

#include "mx.h"
//#include "adc.h"
#include "crc.h"
#include "spi.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"


/**
 * ADC1 initialization parameters.
 */
//const MX_ADC1Params_t MX_ADC1InitParams = {
//    .p_adc = &hadc1,
//    .p_mx_init_f = MX_ADC1_Init
//};

/**
 * SPI1 initialization parameters.
 */
const MX_SPIParams_t MX_SPI1InitParams = {
    .p_mx_init_f = MX_SPI1_Init,
    .p_spi_handle  = &hspi1,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .spi_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .spi_dma_tx_irq_n = DMA1_Channel2_IRQn
};

/**
 * CRC initialization parameters.
 */
const MX_CRCParams_t MX_CRCInitParams = {
    .p_crc = &hcrc,
    .p_mx_init_f = MX_CRC_Init
};

/**
 * INT1 ISM330DHCX (PE4) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_INT1_ISM330DHCX_InitParams = {
    MX_GPIO_PE4_Init,
    INT1_ISM330DHCX_EXTI_IRQn,
    INT1_ISM330DHCX_Pin,
    INT1_ISM330DHCX_GPIO_Port
};


/**
 * CS ISM330DHCX (PA4) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_CS_ISM330DHCX_InitParams = {
    MX_GPIO_PA4_Init,
    UsageFault_IRQn, /*!< NOT USED */
    CS_ISM330DHCX_Pin,
    CS_ISM330DHCX_GPIO_Port
};

/**
 * INT1 IIS3DWB (PE3) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_INT1_IIS3DWB_InitParams = {
    MX_GPIO_PE3_Init,
    INT1_IIS3DWB_EXTI_IRQn,
    INT1_IIS3DWB_Pin,
    INT1_IIS3DWB_GPIO_Port
};


/**
 * CS IIS3DWB (PA15) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_CS_IIS3DWB_InitParams = {
    MX_GPIO_PA4_Init,
    UsageFault_IRQn, /*!< NOT USED */
    CS_IIS3DWB_Pin,
    CS_IIS3DWB_GPIO_Port
};

/**
 * TIM16 initialization parameters.
 */
const MX_TIMParams_t MX_TIM17InitParams = {
    .p_mx_init_f = MX_TIM17_Init,
    .p_tim = &htim17,
    .irq_n = TIM1_TRG_COM_TIM17_IRQn
};

/**
 * PE1 Initialization parameters.
 */
//const MX_GPIOParams_t MX_GPIO_PE1InitParams = {
//    MX_GPIO_PE1_Init,
//    UsageFault_IRQn, /*!< NOT USED */
//    GPIO_PIN_1,
//    GPIOE
//};

/**
 * PE0 Initialization parameters.
 */
//const MX_GPIOParams_t MX_GPIO_PE0InitParams = {
//    MX_GPIO_PE0_Init,
//    UsageFault_IRQn, /*!< NOT USED */
//    GPIO_PIN_0,
//    GPIOE
//};

/**
 * PD12 Initialization parameters.
 */
//const MX_GPIOParams_t MX_GPIO_PD12InitParams = {
//    MX_GPIO_PD12_Init,
//    UsageFault_IRQn, /*!< NOT USED */
//    GPIO_PIN_12,
//    GPIOD
//};

/**
  * (USER_BUTTON) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_UBInitParams =
{
  MX_GPIO_PB13_Init,
  BUTTON_USER_EXTI_IRQn,
  BUTTON_USER_Pin,
  BUTTON_USER_GPIO_Port
};

/**
  * LED1 (Green) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD1InitParams =
{
  MX_GPIO_PD2_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_GREEN_Pin,
  LED_GREEN_GPIO_Port
};

/**
  * LED3 (Red) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD3InitParams =
{
  MX_GPIO_PD8_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_RED_Pin,
  LED_RED_GPIO_Port
};

/**
  * LED2 (Blue) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD2InitParams =
{
  MX_GPIO_PH1_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_BLUE_Pin,
  LED_BLUE_GPIO_Port
};

